server:
  port: 1024
  servlet:
    context-path: /tsc/api
springdoc:
  show-actuator: true
mybatis-plus:
  mapper-locations: classpath*:com/citi/techfest/ikigai/tsc/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl