mybatis-plus:
  mapper-locations: classpath*:com/citi/techfest/ikigai/tsc/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    url: jdbc:mysql://222.65.124.213:3306/ikigaidb
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
