package com.citi.techfest.ikigai.tsc.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;

public class CaseWorker {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "Role")
    private String role;

    @DynamoDBRangeKey(attributeName = "Name")
    private String name;

    @DynamoDBAttribute(attributeName = "ContactNumber")
    private String contactNumber;

    @DynamoDBAttribute(attributeName = "Email")
    private String email;

    // used for caseworkers of an organization
    @DynamoDBAttribute(attributeName = "OrganizationName")
    private String organizationName;

    @DynamoDBAttribute(attributeName = "ServiceCategory")
    private String serviceCategory;

    @DynamoDBHashKey(attributeName = "ServiceName")
    private String serviceName;


}
