package com.citi.techfest.ikigai.tsc.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

import java.time.LocalDate;
import java.util.List;

@Data
@DynamoDBTable(tableName = "Participant")
public class Participant {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "Role")
    private String role;

    @DynamoDBRangeKey(attributeName = "Name")
    private String name;

    @DynamoDBAttribute(attributeName = "Gender")
    private String gender;

    @DynamoDBAttribute(attributeName = "ContactNumber")
    private String contactNumber;

    @DynamoDBAttribute(attributeName = "Email")
    private String email;

    @DynamoDBAttribute(attributeName = "DateOfBirth")
    private String dateOfBirth;

    //only used in beneficiary
    @DynamoDBAttribute(attributeName = "CabinNumber")
    private String cabinNumber;

    @DynamoDBAttribute(attributeName = "MoveInDate")
    private LocalDate moveInDate;

    @DynamoDBAttribute(attributeName = "LeaveDate")
    private LocalDate leaveDate;

    @DynamoDBAttribute(attributeName = "LeaveReason")
    private String leaveReason;

    @DynamoDBAttribute(attributeName = "Comments")
    private String comments;

    @DynamoDBAttribute(attributeName = "AssignedNavigator")
    private String assignedNavigator;

    private List<ServicePlan> servicePlanList;

}

